POST https://node-mailer-dev-aqgf.3.us-1.fl0.io/sendMail
Content-Type: application/json

{
  "to": "megalodon621@gmail.com",
  "subject": "test",
  "html": "<h1>Hello from gmail email using API</h1>"
}

